// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2JixL0j212TZzIWWB37hK7Ysqujiv2c',
    appId: '1:885322918652:web:d93f3e40837f616468c579',
    messagingSenderId: '885322918652',
    projectId: 'romaneio-fc637',
    authDomain: 'romaneio-fc637.firebaseapp.com',
    databaseURL: 'https://romaneio-fc637-default-rtdb.firebaseio.com',
    storageBucket: 'romaneio-fc637.appspot.com',
    measurementId: 'G-6ZZTQT2C89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmj4h2z2rwuIKsQuSDJRsmTM4h_19I3k',
    appId: '1:885322918652:android:7481ef97ccbf13be68c579',
    messagingSenderId: '885322918652',
    projectId: 'romaneio-fc637',
    databaseURL: 'https://romaneio-fc637-default-rtdb.firebaseio.com',
    storageBucket: 'romaneio-fc637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1yHMj9AhhNWM4wnjGVC5YLooI7Cvsoo',
    appId: '1:885322918652:ios:8a40666ed7d686e368c579',
    messagingSenderId: '885322918652',
    projectId: 'romaneio-fc637',
    databaseURL: 'https://romaneio-fc637-default-rtdb.firebaseio.com',
    storageBucket: 'romaneio-fc637.appspot.com',
    iosBundleId: 'com.example.romaneioTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1yHMj9AhhNWM4wnjGVC5YLooI7Cvsoo',
    appId: '1:885322918652:ios:ae5a4895f473a41b68c579',
    messagingSenderId: '885322918652',
    projectId: 'romaneio-fc637',
    databaseURL: 'https://romaneio-fc637-default-rtdb.firebaseio.com',
    storageBucket: 'romaneio-fc637.appspot.com',
    iosBundleId: 'com.example.romaneioTeste.RunnerTests',
  );
}
